services:
  cfmp-user:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=cfmp_db
      - DB_USER=root
      - DB_PASSWORD=123456
      # 使用远程MinIO
      - MINIO_STORAGE_ENDPOINT=47.94.167.198:9000
      - MINIO_STORAGE_ACCESS_KEY=80rhHcZMlWxc7V3kT4Rs
      - MINIO_STORAGE_SECRET_KEY=rKxfuJdaTwcjiu9YIsn3R4UCR9Q39Ft8ywK4LVCi
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cfmp_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: