apiVersion: v1
kind: ConfigMap
metadata:
  name: cfmp-user-config
  namespace: default
data:
  # Django settings
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  
  # Database configuration
  DB_HOST: "cfmp-mysql-service"
  DB_PORT: "3306"
  DB_NAME: "cfmp_db"
  
  # MinIO configuration (使用您现有的远程MinIO)
  MINIO_STORAGE_ENDPOINT: "47.94.167.198:9000"
  MINIO_STORAGE_USE_HTTPS: "False"
  MINIO_STORAGE_MEDIA_BUCKET_NAME: "cfmp"
  MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET: "True"
---
apiVersion: v1
kind: Secret
metadata:
  name: cfmp-user-secrets
  namespace: default
type: Opaque
data:
  # 注意：这些值需要进行 base64 编码
  DB_USER: "cm9vdA=="  # root 的 base64 编码
  DB_PASSWORD: "MTIzNDU2"  # 123456 的 base64 编码
  MINIO_STORAGE_ACCESS_KEY: "ODByaEhjWk1sV3hjN1Yza1Q0UnM="  # 实际值的 base64 编码
  MINIO_STORAGE_SECRET_KEY: "ckt4ZnVKZGFUd2NqaXU5WUlzbjNSNFVDUjlRMzlGdDh5d0s0TFZDaQ=="  # 实际值的 base64 编码
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfmp-user
  namespace: default
  labels:
    app: cfmp-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cfmp-user
  template:
    metadata:
      labels:
        app: cfmp-user
    spec:
      containers:
      - name: cfmp-user
        image: cfmp-user:latest  # 这个会在流水线中被替换
        ports:
        - containerPort: 8000
        env:
        # Django settings
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: cfmp-user-config
              key: DEBUG
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: cfmp-user-config
              key: ALLOWED_HOSTS
              
        # Database configuration
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: cfmp-user-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: cfmp-user-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: cfmp-user-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cfmp-user-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cfmp-user-secrets
              key: DB_PASSWORD
              
        # MinIO configuration
        - name: MINIO_STORAGE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: cfmp-user-config
              key: MINIO_STORAGE_ENDPOINT
        - name: MINIO_STORAGE_USE_HTTPS
          valueFrom:
            configMapKeyRef:
              name: cfmp-user-config
              key: MINIO_STORAGE_USE_HTTPS
        - name: MINIO_STORAGE_MEDIA_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: cfmp-user-config
              key: MINIO_STORAGE_MEDIA_BUCKET_NAME
        - name: MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET
          valueFrom:
            configMapKeyRef:
              name: cfmp-user-config
              key: MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET
        - name: MINIO_STORAGE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cfmp-user-secrets
              key: MINIO_STORAGE_ACCESS_KEY
        - name: MINIO_STORAGE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cfmp-user-secrets
              key: MINIO_STORAGE_SECRET_KEY
              
        readinessProbe:
          httpGet:
            path: /user/me/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          
        livenessProbe:
          httpGet:
            path: /user/me/
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: cfmp-user-service
  namespace: default
spec:
  selector:
    app: cfmp-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfmp-mysql
  namespace: default
  labels:
    app: cfmp-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfmp-mysql
  template:
    metadata:
      labels:
        app: cfmp-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cfmp-user-secrets
              key: DB_PASSWORD
        - name: MYSQL_DATABASE
          value: "cfmp_db"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cfmp-mysql-service
  namespace: default
spec:
  selector:
    app: cfmp-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP