
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        imagePullPolicy: Never  # 在 CI/CD 中会被更新
        ports:
        - containerPort: 8000
        env:
        - name: DB_ENGINE
          value: "django.db.backends.mysql"
        - name: DB_NAME
          value: "cfmp-user"
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          value: "xzw2qwQ~"
        - name: DB_HOST
          value: "user-db-service"
        - name: DB_PORT
          value: "3306"
        - name: DEBUG
          value: "True"
        - name: SECRET_KEY
          value: "123"
        - name: NODE_PORT
          value: "30009"
        - name: NODE_IP
          value: 101.200.231.225"
          

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30009
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "cfmp-user"
        - name: MYSQL_ROOT_HOST      # 添加这一行
          value: "%"                 # 允许 root 从任何主机连接
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - -u
            - root
            - -p${MYSQL_ROOT_PASSWORD}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "mysql -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'"
          initialDelaySeconds: 30
          periodSeconds: 5

      volumes:
      - name: mysql-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: user-db-service
spec:
  selector:
    app: user-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
